- TrayTaskGap: 4
  $name: Tray task gap
  $description: Adjusts the space between task area and tray area.
  $type: signed int

- TaskbarBackgroundHorizontalPadding: 4
  $name: Taskbar background horizontal padding
  $description: Adjusts the horizontal padding on both sides of the taskbar background.
  $type: signed int

- TaskbarOffsetY: 6
  $name: Taskbar vertical offset
  $description: Adjusts the vertical offset of the entire taskbar; Padding with the same value will be applied to the top.
  $type: unsigned int

- TaskbarHeight: 78
  $name: Taskbar height
  $description: Adjusts the height of the entire taskbar.
  $type: unsigned int

- TaskbarIconSize: 40
  $name: Taskbar icon size
  $description: Adjusts the width and height of the taskbar icons.
  $type: unsigned int

- TaskbarButtonSize: 70
  $name: Taskbar button size
  $description: Adjusts the width and height of taskbar button (surrounding the icons).
  $type: unsigned int

- TaskbarCornerRadius: 24
  $name: Corner radius of task bar
  $description: Defines the corner rounding of the taskbar.
  $type: unsigned int

- TaskButtonCornerRadius: 16
  $name: Corner radius of the task buttons
  $description: Defines the corner rounding of individual task buttons.
  $type: unsigned int

- FlatTaskbarBottomCorners: false
  $name: Flat bottom corners
  $description: If enabled, the bottom corners of the taskbar will be squared instead of rounded and the taskbar will dock to the edge of the screen. Overrides the taskbar offset setting.
  $type: bool

- TaskbarBackgroundOpacity: 100
  $name: Background opacity percentage
  $type: unsigned int

- TaskbarBackgroundTint: 0
  $name: Background tint percentage (high = greyscale)
  $type: unsigned int

- TaskbarBackgroundLuminosity: 30
  $name: Background luminosity percentage  (high = opaque, low = glassy)
  $type: unsigned int


