- TrayTaskGap: 10
  $name: Tray task gap
  $description: Adjusts the space between the task area and the tray area (Default 10)
  $type: signed int

- TaskbarBackgroundHorizontalPadding: 6
  $name: Taskbar background horizontal padding
  $description: Sets the horizontal padding on both sides of the taskbar background (Default 6)
  $type: signed int

- TaskbarOffsetY: 6
  $name: Taskbar vertical offset
  $description: Moves the taskbar up or down. Padding of the same value is applied to the top (Default 6)
  $type: unsigned int

- TaskbarHeight: 78
  $name: Taskbar height
  $description: Sets the height of the taskbar (Default 78)
  $type: unsigned int

- TaskbarIconSize: 40
  $name: Taskbar icon size
  $description: Defines the width and height of taskbar icons (Default 40)
  $type: unsigned int

- TaskbarButtonSize: 70
  $name: Taskbar button size
  $description: Sets the size of taskbar buttons, which surround the icons (Default 70)
  $type: unsigned int

- TaskbarCornerRadius: 24
  $name: Taskbar corner radius
  $description: Controls how rounded the taskbar corners appear (Default 24)
  $type: unsigned int

- TaskButtonCornerRadius: 16
  $name: Task button corner radius
  $description: Controls how rounded the corners of individual task buttons are (Default 16)
  $type: unsigned int

- FlatTaskbarBottomCorners: false
  $name: Flat bottom corners
  $description: If enabled, the bottom corners of the taskbar will be squared instead of rounded, and the taskbar will dock to the screen edge. This setting overrides the taskbar offset (Default false)
  $type: bool

- TaskbarBackgroundOpacity: 100
  $name: Background opacity
  $description: Adjusts the opacity of the taskbar background. 0 = fully transparent, 100 = fully opaque (Default 100)
  $type: unsigned int

- TaskbarBackgroundTint: 0
  $name: Background tint
  $description: Modifies the taskbar tint level, where higher values increase grayscale effect. Range 0-100 (Default 0)
  $type: unsigned int

- TaskbarBackgroundLuminosity: 30
  $name: Background luminosity
  $description: Adjusts luminosity of the taskbar background. Higher values make it more opaque, lower values make it more glass-like. Range 0-100 (Default 30)
  $type: unsigned int

- TaskbarBorderOpacity: 30
  $name: Taskbar border opacity
  $description: Controls the opacity of the taskbar border. Range 0-100 (Default 30)
  $type: unsigned int

- FullWidthTaskbarBackground: false
  $name: Full-width taskbar background
  $description: If enabled, the taskbar background spans the entire width of the screen (Default false)
  $type: bool

- IgnoreShowDesktopButton: false
  $name: Ignore "Show Desktop" button
  $description: When enabled, the "Show Desktop" button is ignored in width calculations (Default false)
  $type: bool
